In [12]:
import pandas as pd

In [17]:
clients = pd.read_excel('./Case3_Recheio_2024_v2.xlsx', sheet_name = 0, 
                        header=1, usecols="B:D")
products = pd.read_excel('./Case3_Recheio_2024_v2.xlsx', sheet_name = 1,
                         header=1, usecols="B:D")
transactions = pd.read_excel('./Case3_Recheio_2024_v2.xlsx', sheet_name = 2,
                             header=1, usecols="B:D")
client_types = pd.read_excel('./Case3_Recheio_2024_v2.xlsx', sheet_name = 3,
                             header=1, usecols="B:C")

#### Explore

In [24]:
clients.head(3)

   Client ID  ZIP Code  ID Client Type
0         63      2645             217
1        226      2765             201
2        228      1350             206

In [25]:
products.head(3)

   ID Product           Product Description ID Product Category
0      110110  ACUCAR MCHEF BRANCO PAPEL KG     BENS ESSENCIAIS
1      110211      AÇÚCAR SIDUL AMARELO 1KG     BENS ESSENCIAIS
2      110401     OLEO ALIMENTAR MCHEF 1 LT     BENS ESSENCIAIS

In [26]:
transactions.head(3)

        Date  Client ID  ID Product
0 2019-03-01       4442      291708
1 2019-03-01       4442      291726
2 2019-03-01       4442      291756

In [27]:
client_types.head(3)

   ID Client Type Cliente Type Description
0             201       COZINHA PORTUGUESA
1             202         COZINHA ITALIANA
2             203          COZINHA CHINESA